# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca8e2e9d2981a4b4b146cd64200f663790abc498caca3b80e29f4b2b24126a39b84ff0654c106ebd8f9a2ff246fe1c5cb8556f853fdc9de4280b9541546b114

test:
  secret_key_base: fe455d93fa91553cdf517fe8bc744897f270f8d557aeebe6a02f7e7fe39b11092c285c74eb5dc69f95913c4129170fa5f97330027405cad46b6877da8d3a411a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
